### ISSUE TITLE
Current version no longer compatible with php 5.6.30?

### ISSUE THREAD

**Issue by virk** [splitbrain/dokuwiki-plugin-bureaucracy#301] opened 2021-08-04 08:24 UTC
When I updated bureaucracy to current version I got a blank screen. Switching back to old version 2021-02-17 (via TimeMachine) solved this problem.
Can somebody confirm, that the current version is no longer compatible with php 5.6.30?

**Comment by virk** [comment] 2021-08-31 11:13
Can anybody else confirm that current version does not work with php 5.6.30?

**Comment by Klap-in** [comment] 2021-08-31 23:10
Duplicate of #294

**Closed** 2022-01-24 13:38 UTC
